name: Publish to npm

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2.0.2
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - run: bun install

      # Build the package
      - run: bun run build

      # Determine if this is a pre-release
      - name: Check pre-release status
        id: prerelease
        run: |
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            echo "tag=beta" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      # Publish with appropriate tag based on pre-release status
      - name: Publish to NPM
        run: |
          if [[ "${{ steps.prerelease.outputs.tag }}" == "beta" ]]; then
            echo "Publishing as beta..."
            npm publish --tag beta --provenance
          else
            echo "Publishing as latest..."
            npm publish --provenance
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
